- name: set timezone
  timezone:
    name: Africa/Lagos

- name: Update The Apt Repository
  apt:
    update_cache: yes

- name: Copy Docker Script
  copy:
    src: ./docker.sh
    dest: /home/$USER
    owner: $USER
    group: $USER
    mode: 0644
  tags: copied_script

- name: Install Docker on the server
  shell: sudo sh docker.sh
  register: output